// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmxv5iu-S9DKIilcEInKOVRk5ai4UOsvs',
    appId: '1:282460079214:web:0b60767b75dd1922fdd27f',
    messagingSenderId: '282460079214',
    projectId: 'sustainity-dev',
    authDomain: 'sustainity-dev.firebaseapp.com',
    storageBucket: 'sustainity-dev.appspot.com',
    measurementId: 'G-N7BFWQJ5XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNXCwj-Nh3Y1ZO53Bj-vqFUDiNOwwhl9w',
    appId: '1:282460079214:android:566c56184e355611fdd27f',
    messagingSenderId: '282460079214',
    projectId: 'sustainity-dev',
    storageBucket: 'sustainity-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuteXNlqo-JQxVxkhdsG79744EY3dkEFE',
    appId: '1:282460079214:ios:12b28674227982e1fdd27f',
    messagingSenderId: '282460079214',
    projectId: 'sustainity-dev',
    storageBucket: 'sustainity-dev.appspot.com',
    iosBundleId: 'dev.sustainity.sustainityFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuteXNlqo-JQxVxkhdsG79744EY3dkEFE',
    appId: '1:282460079214:ios:12b28674227982e1fdd27f',
    messagingSenderId: '282460079214',
    projectId: 'sustainity-dev',
    storageBucket: 'sustainity-dev.appspot.com',
    iosBundleId: 'dev.sustainity.sustainityFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmxv5iu-S9DKIilcEInKOVRk5ai4UOsvs',
    appId: '1:282460079214:web:9289c2fa0ceb458dfdd27f',
    messagingSenderId: '282460079214',
    projectId: 'sustainity-dev',
    authDomain: 'sustainity-dev.firebaseapp.com',
    storageBucket: 'sustainity-dev.appspot.com',
    measurementId: 'G-BVT4YSXLHC',
  );
}
